# Generated by Django 5.1.2 on 2024-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
