# Generated by Django 5.1.2 on 2024-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_comment_comment_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
