# Generated by Django 5.1.2 on 2024-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cart_total_price_without_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_without_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
