# Generated by Django 5.1.2 on 2024-11-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
