# Generated by Django 5.1.2 on 2024-12-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
    ]
