# Generated by Django 5.1.2 on 2024-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_promocode_alter_product_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
