# Generated by Django 5.1.2 on 2024-12-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_promocode_is_used_promocode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promo_code',
        ),
    ]
