# Generated by Django 5.1.2 on 2024-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_promocode_is_used_remove_promocode_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
