# Generated by Django 5.1.2 on 2024-12-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
