# Generated by Django 5.1.2 on 2024-11-28 12:34

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, null=True, unique=True, validators=[authentication.utils.validate_uz_phone_number])),
                ('pan', models.IntegerField(max_length=16)),
                ('bank_name', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
