# Generated by Django 5.1.2 on 2024-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pan',
            field=models.IntegerField(),
        ),
    ]
