# Generated by Django 5.1.2 on 2024-11-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_card_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expired_at',
        ),
        migrations.AddField(
            model_name='card',
            name='expired_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='expired_year',
            field=models.IntegerField(default=0),
        ),
    ]
