# Generated by Django 5.1.2 on 2024-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_card_created_at_card_created_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
