# Generated by Django 5.1.2 on 2024-12-03 13:27

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_card_qr_code_remove_card_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, null=True, unique=True, validators=[authentication.utils.validate_uz_phone_number])),
                ('pan', models.IntegerField()),
                ('cvv', models.CharField(blank=True, max_length=3)),
                ('bank_name', models.PositiveIntegerField(choices=[(1, 'IPOTEKABANK'), (2, 'QQBBANK'), (3, 'ORIENTFINANSBANK'), (4, 'KAPITALBANK'), (5, 'ASIAALLIANCEBANK')])),
                ('card_name', models.PositiveIntegerField(choices=[(1, 'VISA'), (2, 'MASTERCARD'), (3, 'UZCARD'), (4, 'HUMO')])),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_month', models.IntegerField()),
                ('created_year', models.IntegerField()),
                ('expired_month', models.IntegerField(default=0)),
                ('expired_year', models.IntegerField(default=0)),
            ],
        ),
    ]
