# Generated by Django 5.1.2 on 2024-12-04 16:58

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[authentication.utils.validate_uz_phone_number]),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[authentication.utils.validate_uz_phone_number]),
        ),
    ]
