# Generated by Django 5.1.2 on 2024-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, '---'), (2, 'MALE'), (3, 'FEMALE')], default=1),
        ),
    ]
